export const demoData = {
  "version": 1,
  "start": "2026-09-01",
  "end": "2026-09-29",
  "timezone": "Asia/Tokyo",
  "synthetic": true,
  "tags": [
    {
      "id": "demo-gaba",
      "name": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "order": 0,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-exercise",
      "name": "睡前运动",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "order": 1,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-coffee",
      "name": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "order": 2,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-alcohol",
      "name": "喝了酒",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "order": 3,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-stretch",
      "name": "拉伸",
      "group": "conditions",
      "cycleDays": 3,
      "timestampEnabled": false,
      "order": 4,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-review",
      "name": "每周复盘",
      "group": "conditions",
      "cycleDays": 7,
      "timestampEnabled": false,
      "order": 5,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-good",
      "name": "睡得很好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "order": 6,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-okay",
      "name": "睡得一般",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "order": 7,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-bad",
      "name": "睡得不好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "order": 8,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-headache",
      "name": "头痛了",
      "group": "results",
      "cycleDays": null,
      "timestampEnabled": false,
      "order": 9,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-energy",
      "name": "精神不错",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "order": 10,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-sleep",
      "name": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "order": 11,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-wake",
      "name": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "order": 12,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-nap",
      "name": "午睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "order": 13,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": false
    },
    {
      "id": "demo-old",
      "name": "睡前看屏幕",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "order": 14,
      "createdAt": "2026-08-31T15:00:00.000Z",
      "archived": true
    }
  ],
  "events": [
    {
      "id": "demo-event-0000",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-01T00:17:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0001",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-01T03:48:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0003",
      "tagId": "demo-review",
      "tagName": "每周复盘",
      "group": "conditions",
      "cycleDays": 7,
      "timestampEnabled": false,
      "occurredAt": "2026-09-01T08:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0002",
      "tagId": "demo-stretch",
      "tagName": "拉伸",
      "group": "conditions",
      "cycleDays": 3,
      "timestampEnabled": false,
      "occurredAt": "2026-09-01T09:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0004",
      "tagId": "demo-old",
      "tagName": "睡前看屏幕",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-01T13:30:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0005",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-01T16:06:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0006",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-01T22:34:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0007",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-02T00:31:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0010",
      "tagId": "demo-okay",
      "tagName": "睡得一般",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-02T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0008",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-02T13:47:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0009",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-02T22:21:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0012",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-03T00:06:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0018",
      "tagId": "demo-bad",
      "tagName": "睡得不好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-03T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0019",
      "tagId": "demo-energy",
      "tagName": "精神不错",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-03T02:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0013",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-03T03:07:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0014",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-03T06:19:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0011",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-03T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0015",
      "tagId": "demo-old",
      "tagName": "睡前看屏幕",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-03T13:30:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0016",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-03T14:57:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0017",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-03T23:28:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0022",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-04T00:37:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0026",
      "tagId": "demo-bad",
      "tagName": "睡得不好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-04T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0027",
      "tagId": "demo-headache",
      "tagName": "头痛了",
      "group": "results",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-04T05:15:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0023",
      "tagId": "demo-stretch",
      "tagName": "拉伸",
      "group": "conditions",
      "cycleDays": 3,
      "timestampEnabled": false,
      "occurredAt": "2026-09-04T09:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0021",
      "tagId": "demo-exercise",
      "tagName": "睡前运动",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-04T12:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0020",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-04T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0024",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-04T14:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0025",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-04T23:27:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0030",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-05T00:25:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0037",
      "tagId": "demo-bad",
      "tagName": "睡得不好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-05T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0038",
      "tagId": "demo-energy",
      "tagName": "精神不错",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-05T02:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0031",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-05T03:25:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0032",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-05T06:14:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0033",
      "tagId": "demo-alcohol",
      "tagName": "喝了酒",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-05T11:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0029",
      "tagId": "demo-exercise",
      "tagName": "睡前运动",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-05T12:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0028",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-05T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0034",
      "tagId": "demo-old",
      "tagName": "睡前看屏幕",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-05T13:30:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0035",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-05T15:10:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0036",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-05T23:32:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0041",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-06T00:34:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0045",
      "tagId": "demo-good",
      "tagName": "睡得很好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-06T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0046",
      "tagId": "demo-energy",
      "tagName": "精神不错",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-06T02:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0042",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-06T03:28:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0047",
      "tagId": "demo-nap",
      "tagName": "午睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-06T04:38:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0040",
      "tagId": "demo-exercise",
      "tagName": "睡前运动",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-06T12:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0039",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-06T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0043",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-06T15:21:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0044",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-06T22:27:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0050",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-07T00:47:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0057",
      "tagId": "demo-good",
      "tagName": "睡得很好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-07T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0051",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-07T03:28:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0058",
      "tagId": "demo-headache",
      "tagName": "头痛了",
      "group": "results",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-07T05:15:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0052",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-07T06:42:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0053",
      "tagId": "demo-stretch",
      "tagName": "拉伸",
      "group": "conditions",
      "cycleDays": 3,
      "timestampEnabled": false,
      "occurredAt": "2026-09-07T09:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0049",
      "tagId": "demo-exercise",
      "tagName": "睡前运动",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-07T12:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0048",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-07T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0054",
      "tagId": "demo-old",
      "tagName": "睡前看屏幕",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-07T13:30:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0055",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-07T14:30:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0056",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-07T22:40:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0059",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-09T00:44:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0060",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-09T03:34:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0061",
      "tagId": "demo-old",
      "tagName": "睡前看屏幕",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-09T13:30:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0062",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-09T13:42:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0063",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-09T22:23:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0064",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-10T00:20:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0070",
      "tagId": "demo-okay",
      "tagName": "睡得一般",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-10T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0065",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-10T03:39:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0066",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-10T06:25:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0067",
      "tagId": "demo-stretch",
      "tagName": "拉伸",
      "group": "conditions",
      "cycleDays": 3,
      "timestampEnabled": false,
      "occurredAt": "2026-09-10T09:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0068",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-10T14:46:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0069",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-10T23:04:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0072",
      "tagId": "demo-okay",
      "tagName": "睡得一般",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-11T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0073",
      "tagId": "demo-energy",
      "tagName": "精神不错",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-11T02:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0071",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-11T23:09:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0075",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-12T00:17:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0078",
      "tagId": "demo-bad",
      "tagName": "睡得不好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-12T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0076",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-12T03:13:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0074",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-12T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0077",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-12T14:43:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0079",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-13T00:18:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0084",
      "tagId": "demo-bad",
      "tagName": "睡得不好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-13T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0081",
      "tagId": "demo-stretch",
      "tagName": "拉伸",
      "group": "conditions",
      "cycleDays": 3,
      "timestampEnabled": false,
      "occurredAt": "2026-09-13T09:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0080",
      "tagId": "demo-alcohol",
      "tagName": "喝了酒",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-13T11:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0082",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-13T14:47:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0083",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-13T23:30:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0085",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-14T00:26:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0088",
      "tagId": "demo-okay",
      "tagName": "睡得一般",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-14T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0089",
      "tagId": "demo-nap",
      "tagName": "午睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-14T04:47:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0086",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-14T13:27:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0087",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-14T23:39:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0092",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-15T00:24:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0097",
      "tagId": "demo-good",
      "tagName": "睡得很好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-15T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0093",
      "tagId": "demo-review",
      "tagName": "每周复盘",
      "group": "conditions",
      "cycleDays": 7,
      "timestampEnabled": false,
      "occurredAt": "2026-09-15T08:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0091",
      "tagId": "demo-exercise",
      "tagName": "睡前运动",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-15T12:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0090",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-15T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0094",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-15T16:05:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0095",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-15T18:24:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0096",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-15T23:28:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0099",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-16T00:39:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0103",
      "tagId": "demo-bad",
      "tagName": "睡得不好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-16T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0104",
      "tagId": "demo-headache",
      "tagName": "头痛了",
      "group": "results",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-16T05:15:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0100",
      "tagId": "demo-stretch",
      "tagName": "拉伸",
      "group": "conditions",
      "cycleDays": 3,
      "timestampEnabled": false,
      "occurredAt": "2026-09-16T09:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0105",
      "tagId": "demo-headache",
      "tagName": "头痛了",
      "group": "results",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-16T10:40:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0098",
      "tagId": "demo-exercise",
      "tagName": "睡前运动",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-16T12:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0101",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-16T16:11:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0102",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-16T22:01:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0106",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-17T00:18:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0111",
      "tagId": "demo-okay",
      "tagName": "睡得一般",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-17T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0112",
      "tagId": "demo-energy",
      "tagName": "精神不错",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-17T02:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0107",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-17T03:45:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0108",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-17T06:21:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0109",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-17T14:03:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0110",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-17T22:44:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0115",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-18T00:04:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0120",
      "tagId": "demo-good",
      "tagName": "睡得很好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-18T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0121",
      "tagId": "demo-energy",
      "tagName": "精神不错",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-18T02:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0116",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-18T03:37:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0117",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-18T06:27:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0114",
      "tagId": "demo-exercise",
      "tagName": "睡前运动",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-18T12:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0113",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-18T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0118",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-18T15:04:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0119",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-18T23:25:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0124",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-20T00:11:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0123",
      "tagId": "demo-exercise",
      "tagName": "睡前运动",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-20T12:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0122",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-20T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0125",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-20T13:46:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0126",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-20T23:19:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0128",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-21T00:41:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0133",
      "tagId": "demo-bad",
      "tagName": "睡得不好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-21T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0129",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-21T03:33:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0130",
      "tagId": "demo-alcohol",
      "tagName": "喝了酒",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-21T11:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0127",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-21T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0131",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-21T14:50:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0132",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-21T22:31:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0139",
      "tagId": "demo-good",
      "tagName": "睡得很好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-22T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0140",
      "tagId": "demo-energy",
      "tagName": "精神不错",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-22T02:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0142",
      "tagId": "demo-nap",
      "tagName": "午睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-22T04:21:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0141",
      "tagId": "demo-headache",
      "tagName": "头痛了",
      "group": "results",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-22T05:15:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0136",
      "tagId": "demo-review",
      "tagName": "每周复盘",
      "group": "conditions",
      "cycleDays": 7,
      "timestampEnabled": false,
      "occurredAt": "2026-09-22T08:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0135",
      "tagId": "demo-stretch",
      "tagName": "拉伸",
      "group": "conditions",
      "cycleDays": 3,
      "timestampEnabled": false,
      "occurredAt": "2026-09-22T09:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0134",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-22T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0137",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-22T13:54:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0138",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-22T22:47:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0144",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-23T00:24:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0145",
      "tagId": "demo-bad",
      "tagName": "睡得不好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-23T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0146",
      "tagId": "demo-energy",
      "tagName": "精神不错",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-23T02:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0143",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-23T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0147",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-24T00:09:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0151",
      "tagId": "demo-okay",
      "tagName": "睡得一般",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-24T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0148",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-24T03:25:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0149",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-24T13:36:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0150",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-24T23:26:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0157",
      "tagId": "demo-good",
      "tagName": "睡得很好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-25T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0158",
      "tagId": "demo-energy",
      "tagName": "精神不错",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-25T02:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0154",
      "tagId": "demo-stretch",
      "tagName": "拉伸",
      "group": "conditions",
      "cycleDays": 3,
      "timestampEnabled": false,
      "occurredAt": "2026-09-25T09:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0153",
      "tagId": "demo-exercise",
      "tagName": "睡前运动",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-25T12:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0152",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-25T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0155",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-25T15:30:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0156",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-25T23:19:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0160",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-26T00:32:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0163",
      "tagId": "demo-good",
      "tagName": "睡得很好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-26T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0164",
      "tagId": "demo-headache",
      "tagName": "头痛了",
      "group": "results",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-26T05:15:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0159",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-26T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0161",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-26T15:41:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0162",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-26T23:35:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0165",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-27T00:31:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0169",
      "tagId": "demo-good",
      "tagName": "睡得很好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-27T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0166",
      "tagId": "demo-alcohol",
      "tagName": "喝了酒",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-27T11:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0167",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-27T13:56:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0168",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-27T23:17:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0171",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-28T00:49:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0177",
      "tagId": "demo-good",
      "tagName": "睡得很好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-28T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0172",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-28T03:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0178",
      "tagId": "demo-nap",
      "tagName": "午睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-28T04:31:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0173",
      "tagId": "demo-coffee",
      "tagName": "喝了咖啡",
      "group": "conditions",
      "cycleDays": null,
      "timestampEnabled": false,
      "occurredAt": "2026-09-28T06:12:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0174",
      "tagId": "demo-stretch",
      "tagName": "拉伸",
      "group": "conditions",
      "cycleDays": 3,
      "timestampEnabled": false,
      "occurredAt": "2026-09-28T09:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0170",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-28T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0175",
      "tagId": "demo-sleep",
      "tagName": "入睡",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-28T15:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0176",
      "tagId": "demo-wake",
      "tagName": "起床",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": true,
      "occurredAt": "2026-09-28T22:59:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0181",
      "tagId": "demo-good",
      "tagName": "睡得很好",
      "group": "results",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-29T01:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0180",
      "tagId": "demo-review",
      "tagName": "每周复盘",
      "group": "conditions",
      "cycleDays": 7,
      "timestampEnabled": false,
      "occurredAt": "2026-09-29T08:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    },
    {
      "id": "demo-event-0179",
      "tagId": "demo-gaba",
      "tagName": "吃了 GABA",
      "group": "conditions",
      "cycleDays": 1,
      "timestampEnabled": false,
      "occurredAt": "2026-09-29T13:00:00.000Z",
      "timezone": "Asia/Tokyo",
      "utcOffsetMinutes": 540,
      "synthetic": true
    }
  ]
};
